apiVersion: v1
kind: Service
metadata:
  name: hostel-test-service
  labels:
  app: hostel-deployment
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8091
      nodePort: 8092
      protocol: TCP
  selector:
    app: hostel-deployment
